defaults:
  enabled:        true
  default_locale: en-US
  default_level:  0
  application:
    host:         http://localhost:3000
    key:          99a4435cedb2fb952
    secret:       d379929f11151322a
  logger:
    enabled:      false
    path:         /log/tr8n.log
  cache:
    enabled:      false
    adapter:      memcache
    host:         localhost:11211
    path:         /cache
    version:      1
    timeout:      3600
  localization:
    default_day_names:        [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]
    default_abbr_day_names:   [Sun, Mon, Tue, Wed, Thu, Fri, Sat]
    default_month_names:      [January, February, March, April, May, June, July, August, September, October, November, December]
    default_abbr_month_names: [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]
    custom_date_formats:
      default:                '%m/%d/%Y'            # 07/4/2008
      short_numeric:          '%m/%d'               # 07/4
      short_numeric_year:     '%m/%d/%y'            # 07/4/08
      long_numeric:           '%m/%d/%Y'            # 07/4/2008
      verbose:                '%A, %B %d, %Y'       # Friday, July  4, 2008
      monthname:              '%B %d'               # July 4
      monthname_year:         '%B %d, %Y'           # July 4, 2008
      monthname_abbr:         '%b %d'               # Jul 4
      monthname_abbr_year:    '%b %d, %Y'           # Jul 4, 2008
      date_time:              '%m/%d/%Y at %H:%M'   # 01/03/1010 at 5:30
  site_info:                  # used by the embedded mode
    title:                    "Tr8n Sample Application"           # site title
    contact_email:            "admin@tr8nhub.com"                 # default contact email
    base_url:                 "http://localhost:3001"             # base site url
    default_url:              "/home"
    default_locale:           "en-US"                             # locale of the site default language
    current_locale_method:    "current_locale"                    # application controller method that sets and returns current locale
    user_info:                                                    # used by integrated and embedded modes
      class_name:               User                              # class name for the User object type
      current_user_method:      current_user                      # returns current user object
      methods:                                                    # User object methods mapping
        id:                     "id"
        name:                   "name"
        gender:                 "gender"
        admin:                  "admin?"
        guest:                  "guest?"                          # if current_user is nil, the user is automatically a guest
        mugshot:                "mugshot"
        link:                   "link"
        locale:                 "locale"
